### ISSUE TITLE
Plans to support volt?

### ISSUE THREAD

**Issue by philipmclifton** [wire-elements/modal#404]
Is there a way to make this package support using volt livewire components? 

Required interface [WireElements\Pro\Contracts\BehavesAsModal] 

```<?php

use WireElements\Pro\Components\Modal\Modal;
use function Livewire\Volt\{state};

new class extends Modal {
    public $count = 0;

    public function increment()
    {
        $this->count++;
    }
}

?>

<div>
    hello i should open in modal
</div>
```

**Comment by randy-rebucas** [comment]
You can use this approach.
`<x-secondary-button x-data="" x-on:click.prevent="$dispatch('open-modal', 'create-new')">{{ __('Create New') }}</x-secondary-button>

<x-modal name="create-new" :show="$errors->isNotEmpty()"> 
        <livewire:patient.create />
 </x-modal>`
######
This is your volt component.

`<?php

use function Livewire\Volt\{state};

//

?>

<div>
    <form wire:submit="save" class="p-6">

        <h2 class="text-lg font-medium text-gray-900">
            {{ __('Create new') }}
        </h2>
<input />

        <div class="mt-6 flex justify-end">
            <x-secondary-button x-on:click="$dispatch('close')">
                {{ __('Cancel') }}
            </x-secondary-button>

            <x-primary-button class="ms-3">
                {{ __('Submit') }}
            </x-primary-button>
        </div>
    </form>
</div>`

**Comment by PhiloNL** [comment]
> Is there a way to make this package support using volt livewire components?
> 
> Required interface [WireElements\Pro\Contracts\BehavesAsModal]
> 
> ```
> 
> use WireElements\Pro\Components\Modal\Modal;
> use function Livewire\Volt\{state};
> 
> new class extends Modal {
>     public $count = 0;
> 
>     public function increment()
>     {
>         $this->count++;
>     }
> }
> 
> ?>
> 
> <div>
>     hello i should open in modal
> </div>
> ```

Not at this time unless there is a lot of demand. But I'm happy to accept a PR 😄

**Comment by paianoa** [comment]
I think I found a workaround to use modals with Volt. I duplicated the code of the ModalComponent  abstract class and created a new abstract class called VoltModalComponent that extends Livewire\Volt\Component class instead of Livewire\Component. This class implements LivewireUI\Modal\Contracts\ModalComponent as well. I put VoltModalComponent class in App/Livewire/Volt namespace and then used it as base class for my volt components: 

> test-component.blade.php

```
<?php

use App\Livewire\Volt\VoltModalComponent;

new class extends VoltModalComponent {
    public $var;
}?>

{{$var}}
```
$var will appear inside the modal when requested

> blade caller view

<button x-data  class=" btn btn-primary btn-sm m-0 "
        title="test"
        @click="$dispatch('openModal', { component: 'test-component'}) ">
    <i class="fa fa-pen"></i>
</button>

In my tests It works fine and I converted all livewire modals to volt ones. Obviously, the VoltModalComponent class will not get package updates. 
Hope can help
